DROP TABLE IF EXISTS books ;
DROP TABLE IF EXISTS authors ;

CREATE TABLE BOOKS
(
  ID INTEGER NOT NULL AUTO_INCREMENT,
  BOOK_TITLE VARCHAR(45) NOT NULL,
  BOOK_AUTHOR VARCHAR(45) NOT NULL,
  BOOK_PRICE INTEGER,
  PRIMARY KEY(ID),
  UNIQUE (BOOK_TITLE, BOOK_AUTHOR),
);


